# Import a inicializace

In [1]:
#!/usr/bin/env python
import copy                                  # Kopirovani prvku
import numpy as np                           # Matematicke operace s maticemi
import random                                # Vyber nahodnych prvku
import h5py                                  # Ukladani vah site
import gym                                   # Prostredi Open AI Gym
#from gym import wrappers                    # Nahravani zaznamu
environment = "MountainCar-v0"               # Jmeno prostredi
env = gym.make(environment)                  # Konkretni hra z Open AI Gym
#env = wrappers.Monitor(env, '/home/lachubcz/tmp/cartpole-experiment-1', force=True)

%matplotlib inline
import matplotlib.pyplot as plt
from collections import deque                # Pamet
from __future__ import division              # Deleni realnych cisel (kvuli nizsi verzi Pythonu 2.6)
from tqdm import tnrange, tqdm_notebook      # Progress bar
from sources.profiling import * #profiling - @do_profile(follow=[method, ])
from sources.playing import *
from sources.visualization import *
from sources.agent import *

#Keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras import regularizers
from keras import optimizers
from keras import losses
from keras import metrics

#Tensorflow session
import tensorflow as tf                     # Knihovna Tensorflow
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)
set_session(tf.Session(config=config))

# Parametry
observetime = 200                            # Delka pozorovani
episodes = 5                              # Pocet epizod
games = 25                                   # Pocet her
scores = []                                  # Pole pro ulozeni vysledku na analyzu
episodesList = []                            # Pole pro ulozeni cisel epizod na analyzu
bestScore = float("-inf")                    # Promenna pro ukladani nejlepsiho prubezneho vysledku
best_avg_score = float("-inf")               # Promenna pro ukladani nejlepsiho prumerneho vysledku
actionCount = env.action_space.n             # Pocet vstupu do prostredi
stateSize = env.observation_space.shape[0]   # Pocet vystupu z prostredi
agent = Agent(env)                           # Vytvoreni agenta

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 32)                96        
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 51        
Total params: 675
Trainable params: 675
Non-trainable params: 0
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 32)                96        
_________________________________________________________________
dense_5 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_6 (Den

# Algoritmus

In [2]:
rand_agent_replay(env, agent, 10000, 500, actionCount)

#agent.loadNN("./DDQN-MountainCar-v0.h5")                                     # Nacteni vah NN
#agent.updateTargetNet()                                                      # Nacteni NN do netTarget

for eps in tnrange(episodes, desc='episodes'):
    state = env.reset()                                                   # Resetovani prostredi
    total_reward = 0                                                      # Vynulovani hodnoty za kolo
    
    for t in range(observetime):
        state = np.reshape(state, (1, stateSize))                         # Formatovani
        action = agent.getActionWE(state)                                 # Ziskani akce
        nextState, reward, done, info = env.step(action)                  # Provedeni akce

        agent.remember(state, action, reward, nextState, done)            # Ulozeni stavu do pameti
        agent.trainDQN()                                                  # Trenovani pameti
        
        state = nextState                                                 # Zmena stavu
        total_reward = total_reward + reward                              # Pricteni odmeny za aktualni stav
        
        agent.epsilonActulization()                                       # Aktualizace epsilon
        if done:                                                          # Konec epizody
            #agent.updateTargetNet()                                      # Aktualizace target site
            
            if eps % 50 == 0:
                avg_score = score_estimate(env, agent, games, stateSize)  # Vypocet aktualniho skore
                scores.append(avg_score)                                  # Ulozeni aktualniho skore
                episodesList.append(eps)                                  # Ulozeni aktualniho cisla epizody
                
                print("Episode: {}/{}, epsilon: {:.2}, average score: {}".format(eps, episodes, agent.currentEpsilon, avg_score))
                
                if avg_score > best_avg_score and eps != 0:
                    best_avg_score = avg_score
                    agent_replay(env, agent,  10000, 500, stateSize)
                
                agent.saveNN("./saves/{}-{}.h5" .format(environment, eps))      # Ulozeni site
                
            if total_reward > bestScore:                                  # Bylo dosazeno nejlepsiho skore
                bestScore = total_reward                                  # Nove nejlepsi skore
                print("Episode: {}/{}, epsilon: {:.2}, new best score: {}".format(eps, episodes, agent.currentEpsilon, total_reward))
            break

agent.saveNN("./saves/{}-DONE.h5" .format(environment, eps))                    # Ulozeni site

A Jupyter Widget

State: [[ -4.42544432e-01  -4.54735808e-04]
 [ -3.81539739e-01   3.35950476e-03]
 [ -4.52762619e-01   3.63390664e-03]
 [ -5.72064077e-01  -5.20137439e-03]
 [ -4.84627605e-01  -4.57273613e-04]
 [ -5.97443935e-01   7.62636548e-03]
 [ -4.41496416e-01  -1.39859007e-03]
 [ -5.51124981e-01  -1.64321878e-03]
 [ -5.50503996e-01   1.04028448e-02]
 [ -5.17239510e-01  -8.59671344e-03]
 [ -4.91268623e-01  -2.05773239e-03]
 [ -5.07302482e-01  -6.08342932e-03]
 [ -4.58819794e-01  -5.28065211e-05]
 [ -5.07456879e-01  -1.15648592e-02]
 [ -5.35163769e-01  -2.04188000e-03]
 [ -5.17393877e-01  -3.93046890e-03]
 [ -5.32673597e-01  -1.99511897e-03]
 [ -5.84639263e-01  -3.83596360e-03]
 [ -5.97204332e-01  -6.79028293e-03]
 [ -5.62486829e-01  -1.71407234e-03]
 [ -3.88524404e-01  -4.91640249e-03]
 [ -3.80307287e-01   3.89576006e-03]
 [ -6.04677929e-01  -1.22950748e-03]
 [ -6.71645062e-01  -2.33282684e-03]
 [ -5.65538633e-01   1.16589999e-02]
 [ -6.97547537e-01   2.69826519e-03]
 [ -6.25549356e-01  -9.03480648

np.array([state[i]]): [[-0.59858205  0.01357448]]
Target_f: [[ 0.11278705  0.21942841 -0.25535414]]
Reward[i]: -1.0
aNet: [ 0.10734179  0.21563949 -0.25276074]
np.max(aNet): 0.21563948690891266
np.amax(aNet): 0.21563948690891266
Target_f(second): [[ 0.11278705  0.21942841 -0.7865169 ]]
State: [[ -5.98582054e-01   1.35744812e-02]
 [ -5.12441897e-01  -8.62915481e-04]
 [ -3.16288133e-01   1.62174378e-03]
 [ -5.05048575e-01  -5.42345184e-03]
 [ -4.94984649e-01  -4.46823445e-03]
 [ -4.63001449e-01  -1.05489337e-02]
 [ -5.39015824e-01   1.43682488e-02]
 [ -4.16538461e-01   1.40740887e-02]
 [ -4.41848232e-01   1.18231426e-02]
 [ -5.72344229e-01  -1.44034054e-02]
 [ -5.18172269e-01   9.20261355e-04]
 [ -4.95184581e-01   6.02738003e-03]
 [ -5.40844366e-01  -3.09866751e-03]
 [ -4.91790588e-01  -5.09567176e-03]
 [ -5.11559963e-01  -1.16244270e-03]
 [ -6.08972240e-01   1.16727954e-03]
 [ -6.58636122e-01  -4.40565700e-03]
 [ -5.08553457e-01  -4.63070831e-04]
 [ -6.31221810e-01  -4.58085644e-03]
 [ 

 [ 0.08352011  0.12490682 -0.87593305]]
State: [[ -5.80974615e-01   4.15162618e-03]
 [ -5.31092781e-01  -9.56436894e-04]
 [ -4.60627677e-01   5.75109108e-03]
 [ -5.01468446e-01   5.97782772e-04]
 [ -4.44738006e-01  -1.04773165e-02]
 [ -4.70270239e-01   8.43735481e-03]
 [ -3.00562089e-01   8.80572045e-03]
 [ -5.15671717e-01   0.00000000e+00]
 [ -4.44031583e-01   5.66255438e-03]
 [ -6.47946232e-01  -7.92824451e-04]
 [ -6.83152768e-01  -8.58058037e-03]
 [ -5.43625728e-01   2.25266499e-03]
 [ -8.38955685e-01   6.44560105e-03]
 [ -4.96014504e-01   7.05364147e-03]
 [ -4.18640469e-01  -2.87122251e-03]
 [ -4.86255095e-01   7.09495044e-03]
 [ -4.84804321e-01   5.56572866e-03]
 [ -4.42172943e-01   8.80802670e-03]
 [ -5.50699692e-01  -2.40639268e-02]
 [ -5.35168011e-01  -5.16481438e-03]
 [ -6.29070144e-01  -3.64528938e-03]
 [ -5.22567685e-01   7.12417155e-03]
 [ -5.98979619e-01  -7.61325109e-03]
 [ -5.75110295e-01  -2.86691149e-03]
 [ -4.87811892e-01  -2.11076638e-04]
 [ -5.33706642e-01  -1.13830

np.array([state[i]]): [[-0.42474994  0.00513593]]
Target_f: [[ 0.02608082  0.07026697 -0.2931087 ]]
Reward[i]: -1.0
aNet: [ 0.02807596  0.06776232 -0.28762418]
np.max(aNet): 0.06776232272386551
np.amax(aNet): 0.06776232272386551
Target_f(second): [[-0.93291533  0.07026697 -0.2931087 ]]
State: [[ -4.24749944e-01   5.13592697e-03]
 [ -5.01464775e-01   6.55421768e-03]
 [ -5.86250913e-01  -5.95022879e-03]
 [ -4.74570468e-01   5.64129147e-03]
 [ -6.14587069e-01   5.88888405e-04]
 [ -4.48512757e-01  -5.68451130e-03]
 [ -4.19973116e-01  -3.59351609e-03]
 [ -4.79659728e-01  -7.28877723e-03]
 [ -4.60922030e-01  -1.41094562e-02]
 [ -5.02137296e-01  -4.44041909e-03]
 [ -4.98730126e-01   1.44955608e-03]
 [ -4.95709095e-01  -1.20991101e-02]
 [ -5.04977235e-01   5.13383027e-03]
 [ -6.02945359e-01   1.72585986e-02]
 [ -4.59839163e-01  -1.47409207e-03]
 [ -6.77328291e-01   5.38957316e-03]
 [ -6.79299847e-01  -7.48638066e-03]
 [ -4.41379385e-01   6.20073444e-03]
 [ -5.90393907e-01  -4.27772804e-03]
 [ 

 [ -9.74661298e-03  -9.50751662e-01  -3.33597571e-01]]
State: [[ -5.50619804e-01   4.78666197e-03]
 [ -5.16810046e-01  -4.77964282e-03]
 [ -5.21922176e-01   2.84482563e-03]
 [ -6.00980052e-01  -2.29318001e-02]
 [ -5.50865794e-01   5.28846071e-03]
 [ -5.14012961e-01  -1.54399056e-02]
 [ -5.17180408e-01  -3.09299752e-03]
 [ -5.39293149e-01   1.24161616e-02]
 [ -4.98619487e-01  -8.57335077e-03]
 [ -5.85464834e-01  -1.11020633e-02]
 [ -4.95573548e-01  -9.21449314e-03]
 [ -4.31607761e-01   1.27367204e-02]
 [ -5.21147199e-01   2.75292522e-03]
 [ -4.96780278e-01   1.37876737e-03]
 [ -6.37222267e-01   9.91323573e-03]
 [ -6.80065791e-01   9.28637864e-03]
 [ -5.83899314e-01  -2.46163266e-03]
 [ -5.01453175e-01   3.44489816e-03]
 [ -4.04094331e-01   3.56670036e-03]
 [ -5.76121077e-01   1.07778465e-02]
 [ -5.07456879e-01  -1.15648592e-02]
 [ -5.70601475e-01   4.80431528e-03]
 [ -5.26543705e-01   5.76104105e-03]
 [ -4.54648311e-01  -8.17838773e-03]
 [ -5.07778304e-01   1.29727568e-03]
 [ -5.5497192

 [ -2.64464132e-03  -9.70025659e-01  -4.16744053e-01]]
State: [[ -5.01468446e-01   5.97782772e-04]
 [ -7.33486705e-01   3.43831838e-03]
 [ -5.42276879e-01  -1.03863523e-02]
 [ -5.58923488e-01  -6.07557337e-03]
 [ -3.85125620e-01   2.32685591e-03]
 [ -7.36303551e-01   6.09165065e-03]
 [ -5.48658197e-01  -3.48178247e-04]
 [ -5.00392888e-01  -9.84858981e-03]
 [ -5.90363315e-01  -3.93354283e-04]
 [ -5.55139698e-01   2.03939754e-03]
 [ -3.51381441e-01   7.83014085e-03]
 [ -7.30625785e-01  -7.22509378e-03]
 [ -5.40230828e-01  -1.34226293e-03]
 [ -4.52082573e-01  -6.06363890e-03]
 [ -6.22537140e-01  -1.12727894e-02]
 [ -5.28009047e-01   5.38725517e-05]
 [ -5.76549425e-01   3.38200369e-03]
 [ -4.11434744e-01   2.11458990e-03]
 [ -5.32689645e-01  -5.69838907e-03]
 [ -4.97975345e-01  -3.23744951e-04]
 [ -4.89176405e-01  -1.33863084e-02]
 [ -5.02804737e-01   1.78090898e-03]
 [ -5.47804753e-01  -1.39251416e-02]
 [ -5.78350510e-01   1.17127755e-02]
 [ -5.29939327e-01   3.53963445e-03]
 [ -5.5766351

np.array([state[i]]): [[-0.56182941  0.00560221]]
Target_f: [[-0.06881142 -0.02059188 -0.5571366 ]]
Reward[i]: -1.0
aNet: [-0.06758962 -0.02150789 -0.55153006]
np.max(aNet): -0.021507885307073593
np.amax(aNet): -0.021507885307073593
Target_f(second): [[-1.02129281 -0.02059188 -0.5571366 ]]
State: [[ -5.61829410e-01   5.60220509e-03]
 [ -4.65678476e-01   1.97097231e-03]
 [ -4.93117512e-01   2.06965769e-03]
 [ -5.30330332e-01   8.32179381e-03]
 [ -5.03743380e-01  -4.40588587e-03]
 [ -5.87555095e-01   3.84074699e-03]
 [ -4.88065256e-01   8.19533467e-03]
 [ -6.64874704e-01  -1.39983861e-03]
 [ -5.41245949e-01   5.33100768e-03]
 [ -4.53320040e-01   1.24558167e-03]
 [ -5.09150496e-01   4.82472736e-03]
 [ -4.03576082e-01  -4.45995196e-03]
 [ -4.87811892e-01  -2.11076638e-04]
 [ -5.40335570e-01   3.41361328e-03]
 [ -4.57732372e-01  -5.21814376e-04]
 [ -5.60653503e-01   1.24255134e-02]
 [ -4.55352974e-01  -3.32641298e-03]
 [ -7.94593661e-01   1.79802567e-02]
 [ -5.67687061e-01  -2.57822967e-03]

 [-0.09261772 -0.05909362 -1.0570786 ]]
State: [[ -5.17036069e-01   3.50846073e-04]
 [ -5.71650395e-01  -2.28078806e-03]
 [ -4.82445031e-01   2.10329982e-02]
 [ -6.06431026e-01   7.27669291e-04]
 [ -6.90447133e-01  -5.51441844e-03]
 [ -6.58756044e-01  -7.49348550e-03]
 [ -4.34656596e-01   5.24091892e-03]
 [ -5.68157376e-01  -6.34270169e-04]
 [ -3.81055176e-01  -4.64996896e-03]
 [ -5.02730047e-01   5.29863916e-03]
 [ -3.74660860e-01   2.79255839e-03]
 [ -5.02767715e-01  -4.94144520e-03]
 [ -5.79328931e-01  -1.40321240e-02]
 [ -5.06056369e-01  -7.49900263e-03]
 [ -4.76583113e-01  -1.94824909e-03]
 [ -5.13930939e-01   4.82961853e-03]
 [ -4.56067287e-01   8.39300432e-03]
 [ -5.69112145e-01   5.38758336e-03]
 [ -5.77082958e-01  -6.09034592e-04]
 [ -4.09329906e-01   4.40847307e-03]
 [ -5.58358714e-01   5.02555721e-03]
 [ -6.24600943e-01  -1.04335812e-02]
 [ -5.02180355e-01  -1.59842160e-02]
 [ -5.16112534e-01  -2.29526814e-03]
 [ -5.05510971e-01  -6.56076855e-03]
 [ -3.87368623e-01   7.06931

np.array([state[i]]): [[ -5.73118716e-01  -4.73378300e-04]]
Target_f: [[-0.13270989 -0.13459229 -0.68137425]]
Reward[i]: -1.0
aNet: [-0.13192157 -0.13520753 -0.68100876]
np.max(aNet): -0.13192157447338104
np.amax(aNet): -0.13192157447338104
Target_f(second): [[-1.13060236 -0.13459229 -0.68137425]]
State: [[ -5.73118716e-01  -4.73378300e-04]
 [ -4.14621176e-01  -3.33711850e-03]
 [ -5.22963383e-01  -5.69990675e-03]
 [ -5.25889867e-01  -3.73853659e-03]
 [ -6.60269231e-01  -1.02690710e-02]
 [ -5.58466085e-01  -5.13118682e-04]
 [ -5.76102171e-01  -1.10255393e-02]
 [ -4.76588263e-01  -1.04069886e-02]
 [ -4.51182053e-01   2.97012825e-03]
 [ -4.84720610e-01  -2.97379644e-03]
 [ -5.46573848e-01   5.49908105e-03]
 [ -4.19186481e-01  -1.67827613e-02]
 [ -5.83002956e-01  -2.52814935e-03]
 [ -5.36383444e-01   5.28024485e-03]
 [ -5.39177232e-01   1.12522519e-03]
 [ -5.55103096e-01   2.56041536e-03]
 [ -4.64706950e-01   4.11235217e-04]
 [ -5.70218482e-01  -1.32357918e-02]
 [ -5.80731419e-01   1.94673

 [-0.12416716 -0.15175599 -1.12415552]]
State: [[ -5.08851804e-01   2.61008027e-04]
 [ -4.67271074e-01  -2.12602581e-03]
 [ -5.29004733e-01  -1.11531886e-02]
 [ -6.82682120e-01   6.74722725e-03]
 [ -5.34647537e-01  -5.05176277e-03]
 [ -3.28140310e-01   5.80026338e-03]
 [ -5.15502318e-01   4.67677340e-03]
 [ -4.47886066e-01  -7.83698405e-03]
 [ -4.98730126e-01   1.44955608e-03]
 [ -6.00625753e-01  -2.39524329e-03]
 [ -4.72782303e-01  -3.35421250e-03]
 [ -5.27790979e-01   4.20121855e-03]
 [ -5.70339629e-01  -3.09577378e-03]
 [ -6.71178362e-01   9.01234606e-04]
 [ -6.21257651e-01  -1.05655379e-02]
 [ -4.98573055e-01  -1.42523890e-02]
 [ -6.41869895e-01  -3.45364133e-03]
 [ -5.24944543e-01  -9.63757473e-03]
 [ -4.79097173e-01   2.39166784e-03]
 [ -5.09991655e-01   1.74597000e-02]
 [ -4.68715845e-01   4.52150616e-03]
 [ -4.48657463e-01  -1.83178491e-03]
 [ -5.27272981e-01   2.61968758e-03]
 [ -5.17447530e-01   2.67020335e-03]
 [ -6.56529043e-01  -1.09341300e-02]
 [ -5.13930939e-01   4.82961

np.array([state[i]]): [[-0.53273212 -0.00547033]]
Target_f: [[-0.18806668 -0.23036729 -0.74313211]]
Reward[i]: -1.0
aNet: [-0.19076718 -0.23051725 -0.75073558]
np.max(aNet): -0.19076718389987946
np.amax(aNet): -0.19076718389987946
Target_f(second): [[-0.18806668 -0.23036729 -1.18885946]]
State: [[ -5.32732122e-01  -5.47033048e-03]
 [ -4.69562340e-01  -3.27935795e-03]
 [ -5.07337557e-01   3.92663398e-03]
 [ -4.76664457e-01  -8.11922613e-04]
 [ -5.13032674e-01   0.00000000e+00]
 [ -5.27375633e-01  -2.75179638e-03]
 [ -4.42127497e-01  -9.44606356e-03]
 [ -5.40186702e-01  -1.16784661e-02]
 [ -4.75375549e-01  -5.13949566e-03]
 [ -4.60675144e-01  -5.22270275e-03]
 [ -5.29865303e-01  -4.86681236e-03]
 [ -5.75091984e-01  -3.12815844e-03]
 [ -5.05550164e-01  -5.54286868e-03]
 [ -5.69044286e-01   1.16908490e-03]
 [ -5.01963519e-01  -1.58838120e-02]
 [ -7.48269656e-01  -2.85335952e-03]
 [ -3.81986127e-01  -1.04035758e-02]
 [ -5.11559963e-01  -1.16244270e-03]
 [ -2.66040552e-01   4.66331481e-03]
 

 [-1.22638297 -0.24432194 -0.80099607]]
State: [[ -5.31914627e-01   1.37501855e-02]
 [ -3.94729632e-01  -3.79264603e-03]
 [ -5.51952762e-01  -1.35564427e-02]
 [ -4.96757748e-01  -1.07826202e-02]
 [ -4.79827116e-01   6.28536831e-04]
 [ -5.24833424e-01   9.85382661e-04]
 [ -5.66316713e-01  -5.81823012e-04]
 [ -4.16538461e-01   1.40740887e-02]
 [ -5.19730067e-01   3.99853897e-04]
 [ -5.10397521e-01  -1.06345917e-03]
 [ -6.07199445e-01  -1.00938836e-02]
 [ -5.00004552e-01   2.03287600e-03]
 [ -5.24767002e-01   3.83606395e-03]
 [ -5.36782649e-01   4.46329966e-03]
 [ -4.00083410e-01  -7.65001191e-03]
 [ -4.81932036e-01  -9.73200203e-03]
 [ -4.88557964e-01  -1.52860688e-03]
 [ -5.89911589e-01   6.07019064e-04]
 [ -6.38060058e-01  -1.85337236e-02]
 [ -4.76719116e-01   2.02225455e-03]
 [ -5.33673721e-01   3.45335546e-03]
 [ -5.51798213e-01  -1.16147125e-03]
 [ -5.54700514e-01   1.45773631e-03]
 [ -5.44727022e-01   4.27085782e-03]
 [ -3.99693946e-01  -1.05919396e-02]
 [ -6.27567089e-01   1.18739

np.array([state[i]]): [[-0.59232481  0.00152298]]
Target_f: [[-0.30514005 -0.32770476 -0.95989221]]
Reward[i]: -1.0
aNet: [-0.30638793 -0.32544193 -0.95943069]
np.max(aNet): -0.30638793110847473
np.amax(aNet): -0.30638793110847473
Target_f(second): [[-0.30514005 -0.32770476 -1.3033241 ]]
State: [[ -5.92324812e-01   1.52297617e-03]
 [ -6.16174918e-01   1.08103119e-04]
 [ -5.63930333e-01   3.50698767e-03]
 [ -5.37299207e-01  -1.43432688e-02]
 [ -4.63755067e-01  -4.17747221e-04]
 [ -5.06666975e-01  -1.64062469e-03]
 [ -5.00521299e-01  -5.34254066e-03]
 [ -5.09451561e-01  -3.15452054e-03]
 [ -4.56286025e-01  -8.39995926e-03]
 [ -5.28120184e-01   2.82325156e-03]
 [ -5.42860227e-01   2.62787038e-03]
 [ -4.83852762e-01   1.29880564e-03]
 [ -6.67567119e-01  -3.45680357e-03]
 [ -5.31725325e-01  -2.82741265e-03]
 [ -3.04187574e-01  -6.43203568e-03]
 [ -5.61127341e-01  -2.78590858e-03]
 [ -4.32577633e-01  -7.80415917e-03]
 [ -5.14143814e-01  -1.10230396e-03]
 [ -6.60453052e-01  -6.36356828e-04]
 

 [-1.32860422 -0.35664758 -0.99200284]]
State: [[ -5.73037834e-01  -2.60619162e-04]
 [ -5.19930403e-01   6.99950667e-03]
 [ -4.80832384e-01   8.54447879e-03]
 [ -5.09546942e-01  -6.36546025e-04]
 [ -5.91228900e-01   9.80538704e-05]
 [ -6.55298801e-01   1.14366063e-02]
 [ -5.14513357e-01  -1.87965095e-03]
 [ -5.16894305e-01   9.60206365e-03]
 [ -4.63748822e-01   2.51386370e-03]
 [ -3.79094330e-01   1.06832397e-05]
 [ -5.91492921e-01  -1.30645317e-02]
 [ -5.29635251e-01   1.35728816e-03]
 [ -7.32111005e-01  -8.37222514e-03]
 [ -6.02928961e-01  -3.95211054e-04]
 [ -5.03274252e-01   2.65129842e-04]
 [ -5.10823366e-01  -9.15108464e-04]
 [ -4.72551329e-01  -7.42635070e-03]
 [ -5.30303329e-01   2.55199688e-03]
 [ -5.75943542e-01  -4.24038689e-03]
 [ -4.11145599e-01   2.89145020e-04]
 [ -5.64138058e-01   2.97312641e-03]
 [ -6.15038282e-01  -2.52654578e-03]
 [ -5.02725384e-01  -4.33633635e-03]
 [ -4.47176669e-01  -7.34431916e-04]
 [ -4.40895543e-01   9.70438648e-03]
 [ -5.94234461e-01  -3.10436

np.array([state[i]]): [[-0.59101193  0.00197176]]
Target_f: [[-0.39082569 -0.42767754 -1.06887484]]
Reward[i]: -1.0
aNet: [-0.39035735 -0.42591289 -1.06599855]
np.max(aNet): -0.3903573453426361
np.amax(aNet): -0.3903573453426361
Target_f(second): [[-0.39082569 -1.38645375 -1.06887484]]
State: [[ -5.91011928e-01   1.97175907e-03]
 [ -5.52106186e-01  -1.19888068e-02]
 [ -6.11807573e-01   3.40034399e-03]
 [ -5.29524750e-01  -1.55117894e-02]
 [ -3.59211582e-01   1.00136736e-02]
 [ -5.78350510e-01   1.17127755e-02]
 [ -4.37778790e-01  -1.44366269e-03]
 [ -5.56909243e-01  -6.22820535e-03]
 [ -4.47788820e-01  -2.90286495e-03]
 [ -5.48463450e-01   5.47697326e-03]
 [ -5.65049828e-01   1.72802461e-03]
 [ -5.42859856e-01   1.47788617e-03]
 [ -6.55133604e-01   3.64470775e-03]
 [ -5.45748116e-01  -3.15762491e-03]
 [ -6.68648531e-01   1.14172591e-02]
 [ -5.40117379e-01  -1.11126457e-02]
 [ -4.55654364e-01   1.10314286e-02]
 [ -5.09482310e-01   1.52783369e-03]
 [ -5.57179096e-01   1.78797092e-03]
 [ 

 [-0.38569704 -0.41417894 -1.37912297]]
State: [[ -4.90370049e-01   4.81453155e-03]
 [ -3.92157950e-01  -2.74417724e-03]
 [ -5.32891061e-01  -1.97546987e-03]
 [ -4.93002104e-01  -4.05838415e-03]
 [ -5.77034339e-01  -4.94317564e-03]
 [ -5.75801860e-01  -8.06821459e-03]
 [ -5.22142947e-01  -6.39973013e-03]
 [ -6.07472034e-01  -1.20518404e-03]
 [ -3.07779895e-01  -1.63432579e-02]
 [ -5.20748062e-01   4.41812054e-03]
 [ -4.51925779e-01  -3.78949771e-04]
 [ -7.45476799e-01  -4.92116850e-03]
 [ -4.00948281e-01   9.81156312e-03]
 [ -5.63914076e-01   1.57794295e-03]
 [ -5.44218587e-01  -8.45080106e-03]
 [ -6.18133094e-01  -1.63325492e-02]
 [ -5.05600554e-01   2.15499378e-04]
 [ -4.29395921e-01  -6.20068343e-03]
 [ -5.86837477e-01   1.48236381e-03]
 [ -5.60737893e-01  -3.96828911e-05]
 [ -4.61786713e-01  -1.12220834e-02]
 [ -4.97358904e-01  -8.12821288e-03]
 [ -4.86658072e-01  -3.38696434e-03]
 [ -6.90861658e-01   4.54841383e-03]
 [ -6.05400547e-01   2.69733892e-03]
 [ -4.51756717e-01  -6.30357

np.array([state[i]]): [[ -5.64291537e-01  -1.00182975e-04]]
Target_f: [[-0.45471138 -0.50923485 -1.12582445]]
Reward[i]: -1.0
aNet: [-0.45603931 -0.5077557  -1.12692487]
np.max(aNet): -0.45603930950164795
np.amax(aNet): -0.45603930950164795
Target_f(second): [[-0.45471138 -0.50923485 -1.45147896]]
State: [[ -5.64291537e-01  -1.00182975e-04]
 [ -5.27029028e-01   2.65165552e-03]
 [ -5.41095335e-01   2.02483974e-03]
 [ -7.28722696e-01   7.58085537e-03]
 [ -5.17615003e-01   1.25132078e-03]
 [ -5.37311500e-01   4.44341189e-03]
 [ -5.17256196e-01  -6.69602390e-03]
 [ -5.97541733e-01  -1.34359684e-02]
 [ -6.26182092e-01  -1.50390328e-02]
 [ -5.44789633e-01  -4.36757870e-03]
 [ -5.13041510e-01  -1.02313771e-03]
 [ -5.77034339e-01  -4.94317564e-03]
 [ -5.85087928e-01  -2.08497258e-03]
 [ -6.33531783e-01  -1.01126806e-02]
 [ -5.35989769e-01  -1.31654489e-02]
 [ -4.14326603e-01   4.05170577e-03]
 [ -4.47728544e-01  -7.64539822e-03]
 [ -5.36025608e-01   2.92242271e-03]
 [ -5.41735130e-01  -5.13886

 [-0.40062556 -1.40023553 -0.953219  ]]
State: [[ -4.63010261e-01   5.88575284e-04]
 [ -3.00562089e-01   8.80572045e-03]
 [ -5.12774230e-01   1.89768698e-03]
 [ -4.67282028e-01   2.52731806e-03]
 [ -4.69562340e-01  -3.27935795e-03]
 [ -5.23315726e-01   4.23454785e-03]
 [ -5.88311596e-01  -7.03783348e-03]
 [ -6.17695279e-01  -4.32376299e-03]
 [ -4.53671375e-01   1.13437598e-02]
 [ -5.28009047e-01   5.38725517e-05]
 [ -5.22323627e-01  -1.23734516e-02]
 [ -4.98661592e-01   5.59032669e-03]
 [ -3.98171000e-01   1.44497713e-02]
 [ -4.02841030e-01   9.44433084e-03]
 [ -4.64048009e-01  -1.38770714e-03]
 [ -4.97651600e-01  -1.29337600e-04]
 [ -3.64876058e-01   7.30504220e-03]
 [ -5.62758388e-01   7.36002567e-03]
 [ -6.46108295e-01  -2.31704443e-02]
 [ -5.22152729e-01  -2.68345286e-04]
 [ -3.82940788e-01  -1.74863780e-03]
 [ -5.07542141e-01   3.18137676e-03]
 [ -4.36661450e-01  -4.22579254e-03]
 [ -4.22168259e-01   7.99917812e-03]
 [ -3.72181101e-01   7.40202023e-03]
 [ -5.33771759e-01   1.70336

np.array([state[i]]): [[-0.55825197  0.00172769]]
Target_f: [[-0.54669875 -0.59102631 -1.23616111]]
Reward[i]: -1.0
aNet: [-0.54470444 -0.59059358 -1.23242497]
np.max(aNet): -0.5447044372558594
np.amax(aNet): -0.5447044372558594
Target_f(second): [[-1.53925741 -0.59102631 -1.23616111]]



KeyboardInterrupt: 

# Interpretace výsledků

In [ ]:
analysis(scores, episodesList)

In [ ]:
eps = 0
for i in range(1000):
    agent.loadNN("./ki/MountainCar-v0-{}.h5" .format(eps))                                     # Nacteni vah NN
    #agent.updateTargetNet()                                                      # Nacteni NN do netTarget

    avg_score = score_estimate(env, agent, games, stateSize)
    print("Episode: {}, Kernel initializer: {}" .format(eps, avg_score))
    
    eps = eps + 50
    if eps == 1750:
        break
        
eps = 0
for i in range(1000):
    agent.loadNN("./none/MountainCar-v0-{}.h5" .format(eps))                                     # Nacteni vah NN
    #agent.updateTargetNet()                                                      # Nacteni NN do netTarget

    avg_score = score_estimate(env, agent, games, stateSize)
    print("Episode: {}, None: {}" .format(eps, avg_score))
    
    eps = eps + 50
    if eps == 2600:
        break
        
eps = 0
for i in range(1000):
    agent.loadNN("./tn-ki/MountainCar-v0-{}.h5" .format(eps))                                     # Nacteni vah NN
    #agent.updateTargetNet()                                                      # Nacteni NN do netTarget

    avg_score = score_estimate(env, agent, games, stateSize)
    print("Episode: {}, Kernel initializer, Target network: {}" .format(eps, avg_score))
    
    eps = eps + 50
    if eps == 1700:
        break
        
eps = 0
for i in range(1000):
    agent.loadNN("./tn/MountainCar-v0-{}.h5" .format(eps))                                     # Nacteni vah NN
    #agent.updateTargetNet()                                                      # Nacteni NN do netTarget

    avg_score = score_estimate(env, agent, games, stateSize)
    print("Episode: {}, Target network: {}" .format(eps, avg_score))
    
    eps = eps + 50
    if eps == 2400:
        break